version: '3'
services:
  mysql8:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=masterkey
      - MYSQL_DATABASE=odds
      - MYSQL_USER=user_odds
      - MYSQL_PASSWORD=M@st3rkey
    ports:
      - "3306:3306"
networks:
  default:
    external:
      name: odds-network