version: '3'
services:
  odds-ui:
    image: 'lucasdefariasbezerra/odds-repo:odds-ui-image'
    restart: on-failure
    ports:
      - "3000:3000"
networks:
  default:
    external:
      name: odds-network